<?php

require_once BASE_PATH . '/includes/clients.php';

$clientId = (int)($_GET['client_id'] ?? 0);
if (!$clientId) redirect('index.php?page=clients');

$client = getClient($clientId, $_SESSION['user_id']);
if (!$client) { flash('error', 'Client not found.'); redirect('index.php?page=clients'); }

// ── AJAX: latest catalog PDF generated by this user for this client ───────
if (!empty($_GET['ajax_latest_catalog'])) {
    header('Content-Type: application/json');
    $db = getDB();
    $st = $db->prepare("
        SELECT id, name, pages, size_bytes, status, created_at
        FROM catalogs
        WHERE JSON_EXTRACT(config_json, '$._source.client_id') = ?
          AND user_id = ?
        ORDER BY created_at DESC LIMIT 1
    ");
// error_log(sprintf($clientId . $_SESSION['user_id']));
    $st->execute([$clientId, $_SESSION['user_id']]);
    echo json_encode(['catalog' => $st->fetch() ?: null]);
    exit;
}
// ── AJAX: selection history (lazy-loaded via popup — never prefetched) ─────
if (!empty($_GET['ajax_history'])) {
    require_once BASE_PATH . '/includes/selection_history.php';
    header('Content-Type: application/json');
    $hPerPage = 15;
    $hPage    = max(1, (int)($_GET['p'] ?? 1));
    $hResult  = getSelectionHistory($clientId, ['limit' => $hPerPage, 'offset' => ($hPage - 1) * $hPerPage]);
    $hTotal   = $hResult['total'];
    $hPages   = max(1, (int)ceil($hTotal / $hPerPage));
    echo json_encode([
        'success' => true,
        'rows'    => $hResult['rows'],
        'total'   => $hTotal,
        'pages'   => $hPages,
        'current' => min($hPage, $hPages),
    ]);
    exit;
}

$pageTitle = h($client['client_name']) . ' — Selections';
$showNav   = true;
$extraCSS  = ['selection_history.css'];
$extraJS   = ['selection_history.js'];

$perPage     = 10;
$currentPage = max(1, (int)($_GET['p'] ?? 1));
$search      = trim($_GET['q'] ?? '');
$isAjax      = !empty($_GET['ajax']);

$result = getSelections($clientId, $_SESSION['user_id'], [
    'search' => $search,
    'limit'  => $perPage,
    'offset' => ($currentPage - 1) * $perPage,
]);
$selections = $result['rows'];
$total      = $result['total'];
$totalPages = max(1, (int)ceil($total / $perPage));

if ($isAjax) {
    ob_start();
    include BASE_PATH . '/pages/_selection_rows.php';
    $html = ob_get_clean();
    header('Content-Type: application/json');
    echo json_encode(['html' => $html, 'total' => $total, 'pages' => $totalPages, 'current' => $currentPage]);
    exit;
}
?>
<?php include BASE_PATH . '/layouts/header.php'; ?>

<div class="page-content">

  <!-- Back nav -->
  <div style="display:flex;align-items:center;gap:12px;padding-top:20px;margin-bottom:20px;">
    <a href="index.php?page=clients" class="hero-icon-btn" style="flex-shrink:0;"><?= icon('back', 18) ?></a>
    <div style="flex:1;min-width:0;">
      <p class="page-eyebrow">Client Selections</p>
      <h1 class="page-title" style="font-size:22px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">
        <?= h($client['client_name']) ?>
      </h1>
    </div>
    <button type="button" class="btn btn-secondary btn-sm"
            onclick="openSelectionHistory(<?= $clientId ?>, 'index.php?page=client_selections')">
      <?= icon('file', 13) ?>&nbsp;History
    </button>
    <a href="index.php?page=client_form&id=<?= $clientId ?>"
       class="btn btn-secondary btn-sm"><?= icon('edit', 13) ?>&nbsp;Edit</a>
  </div>

  <!-- Client info card -->
  <div class="card" style="padding:16px 20px;margin-bottom:20px;display:flex;flex-wrap:wrap;gap:16px;align-items:flex-start;">
    <div style="display:flex;align-items:center;gap:12px;flex:1;min-width:200px;">
      <div class="client-avatar" style="width:48px;height:48px;font-size:18px;flex-shrink:0;">
        <?= strtoupper(mb_substr($client['client_name'], 0, 1)) ?>
      </div>
      <div>
        <p style="font-weight:700;font-size:15px;"><?= h($client['client_name']) ?></p>
        <a href="tel:<?= h($client['client_mobile']) ?>" style="font-size:13px;color:var(--text3);display:flex;align-items:center;gap:4px;">
          <?= icon('phone', 12) ?> <?= h($client['client_mobile']) ?>
        </a>
      </div>
    </div>
    <?php if ($client['mansoner_name']): ?>
    <div style="flex:1;min-width:160px;">
      <p style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.4px;color:var(--text4);margin-bottom:3px;">Mason</p>
      <p style="font-size:13px;font-weight:600;"><?= h($client['mansoner_name']) ?></p>
      <?php if ($client['mansoner_mobile']): ?>
      <p style="font-size:12px;color:var(--text3);"><?= h($client['mansoner_mobile']) ?></p>
      <?php endif; ?>
    </div>
    <?php endif; ?>
    <?php if ($client['site_address']): ?>
    <div style="flex:2;min-width:200px;">
      <p style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.4px;color:var(--text4);margin-bottom:3px;">Site Address</p>
      <p style="font-size:12px;color:var(--text2);line-height:1.5;"><?= h($client['site_address']) ?></p>
    </div>
    <?php endif; ?>
  </div>
 <!-- Catalog PDF status card -->
  <div class="card" id="selCatalogCard" style="padding:14px 18px;margin-bottom:16px;display:none;">
    <div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap;">
      <div id="selCatalogIcon" style="width:40px;height:40px;border-radius:10px;background:var(--gray-100);color:var(--text3);display:flex;align-items:center;justify-content:center;flex-shrink:0;">
        <?= icon('pdf', 18) ?>
      </div>
      <div style="flex:1;min-width:180px;">
        <p id="selCatalogTitle" style="font-weight:700;font-size:13px;color:var(--text);"></p>
        <p id="selCatalogMeta" style="font-size:12px;color:var(--text3);"></p>
      </div>
      <div style="display:flex;gap:8px;flex-wrap:wrap;">
        <a id="selCatalogDlBtn" href="#" style="display:none;text-decoration:none;" class="btn btn-secondary btn-sm">
          <?= icon('download',13) ?>&nbsp; Download
        </a>
        <button type="button" id="selCatalogEmailBtn" style="display:none;" class="btn btn-secondary btn-sm">
          <?= icon('mail',13) ?>&nbsp; Email
        </button>
      </div>
    </div>
  </div>
  <!-- Search + Add -->
  <div style="display:flex;gap:10px;align-items:center;margin-bottom:16px;flex-wrap:wrap;">
    <div class="catalog-search-wrap" style="flex:1;min-width:200px;margin-bottom:0;">
      <span class="catalog-search-icon"><?= icon('search', 16) ?></span>
      <input type="search" id="selSearch" class="catalog-search-input"
             placeholder="Search product name or lot number…"
             value="<?= h($search) ?>" autocomplete="off"/>
    </div>
    <a href="index.php?page=catalog" class="btn btn-primary btn-sm" style="flex-shrink:0;">
      <?= icon('plus', 14) ?>&nbsp; Add Products
    </a>
    <button type="button" id="selGenPdfBtn" class="btn btn-secondary btn-sm" style="flex-shrink:0;color:var(--danger);border-color:var(--danger);">
      <?= icon('pdf', 14) ?>&nbsp; Generate PDF
    </button>
  </div>
  

  <!-- Count -->
  <div id="selCount" style="font-size:13px;color:var(--text3);margin-bottom:14px;">
    <strong style="font-size:18px;color:var(--text);"><?= $total ?></strong> products selected
  </div>

  <!-- Ajax loader -->
  <div id="selLoader" class="ajax-loader"><div class="loader-spinner"></div></div>

  <!-- Content -->
  <div id="selContent">
    <?php include BASE_PATH . '/pages/_selection_rows.php'; ?>
  </div>

</div>

<!-- Edit Selection Modal -->
<div id="editSelModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9000;align-items:center;justify-content:center;padding:16px;">
  <div style="background:var(--white);border-radius:var(--radius-xl);width:100%;max-width:480px;max-height:90vh;overflow-y:auto;box-shadow:var(--shadow-xl);">
    <div style="padding:20px 22px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;">
      <p style="font-size:16px;font-weight:700;">Edit Selection</p>
      <button id="editSelClose" style="color:var(--text3);cursor:pointer;"><?= icon('close', 18) ?></button>
    </div>
    <div style="padding:22px;">
      <form method="POST" action="index.php" id="editSelForm">
        <input type="hidden" name="action"       value="update_selection"/>
        <input type="hidden" name="selection_id" id="editSelId"/>
        <input type="hidden" name="client_id"    value="<?= $clientId ?>"/>
        <?= csrfField() ?>
        <div class="input-group">
          <label class="input-label">Selection Area / Room</label>
          <input type="text" name="selection_area" id="editSelArea" class="input-field" placeholder="e.g. Master Bedroom" list="roomAreaSuggestions" autocomplete="off"/>
        </div>
        <div class="input-group">
          <label class="input-label">Quantity Required (sqft)</label>
          <input type="number" name="quantity_required" id="editSelQty" class="input-field" min="0" step="0.01" placeholder="0.00"/>
        </div>
        <div class="input-group">
          <label class="input-label">Notes</label>
          <textarea name="extra_notes" id="editSelNotes" class="input-field" rows="3" placeholder="Any special requirements…"></textarea>
        </div>
        <div style="display:flex;gap:10px;">
          <button type="submit" class="btn btn-primary" style="flex:1;"><?= icon('check', 14) ?>&nbsp; Save</button>
          <button type="button" id="editSelCancelBtn" class="btn btn-secondary">Cancel</button>
        </div>
      </form>
    </div>
  </div>
  <?= roomAreaDatalist() ?>
</div>
<!-- Email Selection PDF Modal -->
<div id="selEmailModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9100;align-items:center;justify-content:center;padding:16px;">
  <div style="background:var(--white);border-radius:var(--radius-xl);width:100%;max-width:480px;max-height:90vh;overflow-y:auto;box-shadow:var(--shadow-xl);">
    <div style="padding:18px 22px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;">
      <p style="font-size:16px;font-weight:700;">Email Selection PDF</p>
      <button type="button" id="selEmailClose" style="color:var(--text3);cursor:pointer;background:none;border:none;"><?= icon('close', 18) ?></button>
    </div>
    <div style="padding:20px;">
      <form id="selEmailForm">
        <div class="input-group">
          <label class="input-label">To <span style="color:var(--danger);">*</span></label>
          <input type="text" id="selEmailTo" class="input-field" placeholder="client@example.com" required/>
        </div>
        <div class="input-group">
          <label class="input-label">CC</label>
          <input type="text" id="selEmailCc" class="input-field" placeholder="optional, comma-separated"/>
        </div>
        <div class="input-group">
          <label class="input-label">BCC</label>
          <input type="text" id="selEmailBcc" class="input-field" placeholder="optional, comma-separated"/>
        </div>
        <div class="input-group">
          <label class="input-label">Subject</label>
          <input type="text" id="selEmailSubject" class="input-field"/>
        </div>
        <div class="input-group">
          <label class="input-label">Message</label>
          <textarea id="selEmailMessage" class="input-field" rows="5"></textarea>
        </div>
        <div style="display:flex;gap:10px;">
          <button type="submit" class="btn btn-primary" style="flex:1;" id="selEmailSendBtn">
            <?= icon('mail',15) ?>&nbsp; Send
          </button>
          <button type="button" id="selEmailCancel" class="btn btn-secondary">Cancel</button>
        </div>
        <p id="selEmailStatus" style="font-size:12px;margin-top:10px;"></p>
      </form>
    </div>
  </div>
</div>
<script>
(function () {
  const content  = document.getElementById('selContent');
  const loader   = document.getElementById('selLoader');
  const countEl  = document.getElementById('selCount');
  const searchEl = document.getElementById('selSearch');
  const modal    = document.getElementById('editSelModal');
  const clientId = <?= $clientId ?>;

  let state = { q: <?= json_encode($search) ?>, page: 1 };
  let timer = null;

  async function load(page, push) {
    state.page = page;
    if (loader) loader.style.display = 'flex';
    const params = new URLSearchParams({ page: 'client_selections', ajax: '1', client_id: clientId, p: page });
    if (state.q) params.set('q', state.q);
    try {
      const r = await fetch('index.php?' + params);
      const d = await r.json();
      content.innerHTML = d.html;
      if (countEl) countEl.innerHTML = '<strong style="font-size:18px;color:var(--text);">' + d.total + '</strong> products selected';
      bindButtons();
    } finally {
      if (loader) loader.style.display = 'none';
    }
  }

  function bindButtons() {
    // Pagination
    content.querySelectorAll('.pag-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        if (btn.classList.contains('disabled') || btn.classList.contains('active')) return;
        load(parseInt(btn.dataset.page));
      });
    });
    // Edit buttons
    content.querySelectorAll('.sel-edit-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        document.getElementById('editSelId').value    = btn.dataset.id;
        document.getElementById('editSelArea').value  = btn.dataset.area  || '';
        document.getElementById('editSelQty').value   = btn.dataset.qty   || '';
        document.getElementById('editSelNotes').value = btn.dataset.notes || '';
        modal.style.display = 'flex';
      });
    });
    // Delete buttons
    content.querySelectorAll('.sel-delete-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        if (!confirm('Remove "' + btn.dataset.name + '" from this selection?')) return;
        const form = document.createElement('form');
        form.method = 'POST'; form.action = 'index.php';
        form.innerHTML = '<input type="hidden" name="action" value="delete_selection"/>' +
          '<input type="hidden" name="selection_id" value="' + btn.dataset.id + '"/>' +
          '<input type="hidden" name="client_id" value="' + clientId + '"/>' +
          '<input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"/>';
        document.body.appendChild(form); form.submit();
      });
    });
  }

  // Search
  if (searchEl) {
    searchEl.addEventListener('input', () => {
      const v = searchEl.value.trim();
      clearTimeout(timer);
      if (v.length > 0 && v.length < 3) return;
      timer = setTimeout(() => { state.q = v; load(1); }, 350);
    });
  }

  // Modal close
  document.getElementById('editSelClose')?.addEventListener('click',     () => { modal.style.display = 'none'; });
  document.getElementById('editSelCancelBtn')?.addEventListener('click', () => { modal.style.display = 'none'; });
  modal?.addEventListener('click', e => { if (e.target === modal) modal.style.display = 'none'; });

  // Handle edit form submit via AJAX
  document.getElementById('editSelForm')?.addEventListener('submit', async function (e) {
    e.preventDefault();
    const body = new FormData(this);
    try {
      const r = await fetch('index.php', {
        method: 'POST',
        body,
        headers: { 'X-Requested-With': 'XMLHttpRequest' }
      });
      if (!r.ok) throw new Error('HTTP ' + r.status);
      let d = {};
      try { d = await r.json(); } catch (_) { /* non-JSON success path, ignore */ }
      if (d && d.success === false) throw new Error(d.error || 'Update failed.');
      modal.style.display = 'none';
      load(state.page, false);
    } catch (err) {
      alert('Could not save changes: ' + err.message + '. Please refresh and try again.');
    }
  });
  bindButtons();
  
  // ── Selection PDF generation ────────────────────────────────────────────
  var catalogCard  = document.getElementById('selCatalogCard');
  var catalogTitle = document.getElementById('selCatalogTitle');
  var catalogMeta  = document.getElementById('selCatalogMeta');
  var dlBtn        = document.getElementById('selCatalogDlBtn');
  var emailBtn     = document.getElementById('selCatalogEmailBtn');
  var genBtn       = document.getElementById('selGenPdfBtn');
  var latestCatalogId = null;

  function showCatalogState(state2, opts) {
    opts = opts || {};
    catalogCard.style.display = 'block';
    catalogTitle.textContent = opts.title || '';
    catalogMeta.textContent = opts.meta || '';
    if (opts.catalogId) {
      dlBtn.href = 'index.php?catalog_download=1&id=' + opts.catalogId;
      dlBtn.style.display = state2 === 'done' ? '' : 'none';
    } else {
      dlBtn.style.display = 'none';
    }
    emailBtn.style.display = state2 === 'done' ? '' : 'none';
  }

  function loadLatestCatalog() {
    fetch('index.php?page=client_selections&client_id=' + clientId + '&ajax_latest_catalog=1')
      .then(function (r) { return r.json(); })
      .then(function (d) {
        if (!d.catalog) { catalogCard.style.display = 'none'; return; }
        latestCatalogId = d.catalog.id;
        var sizeMb = d.catalog.size_bytes ? (d.catalog.size_bytes / 1048576).toFixed(1) + ' MB' : '';
        var pages  = d.catalog.pages ? d.catalog.pages + ' pages' : '';
        var when   = new Date(d.catalog.created_at * 1000).toLocaleString();
        if (d.catalog.status === 'done') {
          showCatalogState('done', { title: d.catalog.name, meta: [pages, sizeMb, when].filter(Boolean).join(' · '), catalogId: d.catalog.id });
        } else if (d.catalog.status === 'failed') {
          showCatalogState('error', { title: 'Last generation failed', meta: when });
        } else {
          showCatalogState('pending', { title: 'Generating…', meta: when });
        }
      })
      .catch(function () { catalogCard.style.display = 'none'; });
  }

  if (genBtn) {
    genBtn.addEventListener('click', function () {
      if (!confirm('Generate a PDF with all products currently in this selection?')) return;
      genBtn.disabled = true;
      var orig = genBtn.innerHTML;
      genBtn.innerHTML = '<?= icon("refresh",14) ?> Generating…';
      showCatalogState('pending', { title: 'Generating selection PDF…', meta: 'This may take a moment.' });

      var body = new URLSearchParams();
      body.set('action', 'generate_selection_pdf');
      body.set('client_id', clientId);
      body.set('csrf_token', <?= json_encode(csrfToken()) ?>);

      fetch('index.php', { method: 'POST', body: body, headers: { 'X-Requested-With': 'XMLHttpRequest' } })
        .then(function (r) { return r.json(); })
        .then(function (d) {
          if (d.success) {
            latestCatalogId = d.catalog_id;
            showCatalogState('done', {
              title: d.client_name + ' — Selections',
              meta: d.pages + ' pages · ' + (d.size / 1048576).toFixed(1) + ' MB',
              catalogId: d.catalog_id,
            });
          } else {
            showCatalogState('error', { title: 'Generation failed', meta: d.error || 'Unknown error.' });
            alert('Could not generate PDF: ' + (d.error || 'Unknown error.'));
          }
        })
        .catch(function (e) {
          showCatalogState('error', { title: 'Generation failed', meta: e.message });
          alert('Request failed: ' + e.message);
        })
        .finally(function () {
          genBtn.disabled = false;
          genBtn.innerHTML = orig;
        });
    });
  }

  // ── Email modal ──────────────────────────────────────────────────────────
  var emailModal = document.getElementById('selEmailModal');
  function openEmailModal() {
    if (!latestCatalogId) { alert('Generate a PDF first.'); return; }
    document.getElementById('selEmailTo').value = '';
    document.getElementById('selEmailCc').value = '';
    document.getElementById('selEmailBcc').value = '';
    document.getElementById('selEmailSubject').value = 'Your Product Selection Catalog';
    document.getElementById('selEmailMessage').value = 'Hi,\n\nPlease find attached your product selection catalog.\n\nRegards';
    document.getElementById('selEmailStatus').textContent = '';
    emailModal.style.display = 'flex';
  }
  function closeEmailModal() { emailModal.style.display = 'none'; }
  emailBtn && emailBtn.addEventListener('click', openEmailModal);
  document.getElementById('selEmailClose')?.addEventListener('click', closeEmailModal);
  document.getElementById('selEmailCancel')?.addEventListener('click', closeEmailModal);
  emailModal?.addEventListener('click', function (e) { if (e.target === this) closeEmailModal(); });

  document.getElementById('selEmailForm')?.addEventListener('submit', function (e) {
    e.preventDefault();
    var btn = document.getElementById('selEmailSendBtn');
    var status = document.getElementById('selEmailStatus');
    var to = document.getElementById('selEmailTo').value.trim();
    if (!to) { alert('Recipient email is required.'); return; }

    btn.disabled = true;
    status.style.color = 'var(--text3)';
    status.textContent = 'Sending…';

    var body = new URLSearchParams();
    body.set('action', 'send_selection_catalog_email');
    body.set('catalog_id', latestCatalogId);
    body.set('to', to);
    body.set('cc', document.getElementById('selEmailCc').value.trim());
    body.set('bcc', document.getElementById('selEmailBcc').value.trim());
    body.set('subject', document.getElementById('selEmailSubject').value);
    body.set('message', document.getElementById('selEmailMessage').value);
    body.set('csrf_token', <?= json_encode(csrfToken()) ?>);

    fetch('index.php', { method: 'POST', body: body, headers: { 'X-Requested-With': 'XMLHttpRequest' } })
      .then(function (r) { return r.json(); })
      .then(function (d) {
        if (d.success) {
          status.style.color = 'var(--success)';
          status.textContent = 'Sent ✓';
          setTimeout(closeEmailModal, 1200);
        } else {
          status.style.color = 'var(--danger)';
          status.textContent = 'Error: ' + (d.error || 'send failed');
        }
      })
      .catch(function (e) {
        status.style.color = 'var(--danger)';
        status.textContent = 'Request failed: ' + e.message;
      })
      .finally(function () { btn.disabled = false; });
  });
 loadLatestCatalog();
})();
</script>

<?php include BASE_PATH . '/layouts/footer.php'; ?>